permalink: /:categories/:title/
collections:
  units:
    output: false
  lessons:
    output: true
    permalink: /:collection/:title/
  homework:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/
  meetings:
    output: true
    permalink: /:collection/:title/
  outcomes:
    output: true
    permalink: /:collection/:title/
  topics:
    output: true
    permalink: /:collection/:title/
defaults:
  -
    scope:
      path: ""
      type: "lessons"
    values:
      layout: "lesson"
  -
    scope:
      path: ""
      type: "homework"
    values:
      layout: "homework"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "meetings"
    values:
      layout: "meeting"
  -
    scope:
      path: ""
      type: "outcomes"
    values:
      layout: "outcomes"
  -
    scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"

  -
    scope:
      path: "pages/about"
    values:
      layout: "about"
  -
    scope:
      path: "pages/resources"
    values:
      layout: "resources"

  -
    scope:
      path: "_lessons/design-thinking"
    values:
      unit: 1
  -
    scope:
      path: "_lessons/interaction-design"
    values:
      unit: 2
  -
    scope:
      path: "_lessons/information-architecture"
    values:
      unit: 3
  -
    scope:
      path: "_lessons/web-development"
    values:
      unit: 4
  -
    scope:
      path: "_lessons/review"
    values:
      unit: 5
  -
    scope:
      path: "_lessons/careers"
    values:
      unit: 6

  -
    scope:
      path: "_projects/design-thinking"
    values:
      unit: 1
  -
    scope:
      path: "_projects/interaction-design"
    values:
      unit: 2
  -
    scope:
      path: "_projects/information-architecture"
    values:
      unit: 3
  -
    scope:
      path: "_projects/web-development"
    values:
      unit: 4
  -
    scope:
      path: "_projects/review"
    values:
      unit: 5
  -
    scope:
      path: "_projects/careers"
    values:
      unit: 6

  -
    scope:
      path: "_homework/design-thinking"
    values:
      unit: 1
  -
    scope:
      path: "_homework/interaction-design"
    values:
      unit: 2
  -
    scope:
      path: "_homework/information-architecture"
    values:
      unit: 3
  -
    scope:
      path: "_homework/web-development"
    values:
      unit: 4
  -
    scope:
      path: "_homework/review"
    values:
      unit: 5
  -
    scope:
      path: "_homework/careers"
    values:
      unit: 6

relative_permalinks: false
future: false
include: ["_redirects"]
