permalink: /:categories/:title/
collections:
  lessons:
    output: true
    permalink: /:collection/:title/
  homework:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/
defaults:
  -
    scope:
      path: ""
      type: "lessons"
    values:
      layout: "lesson"
  -
    scope:
      path: ""
      type: "homework"
    values:
      layout: "homework"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
relative_permalinks: false
future: false
