permalink: /:categories/:title/
collections:
  units:
    output: false
  lessons:
    output: true
    permalink: /:collection/:title/
  homework:
    output: true
    permalink: /:collection/:title/
  projects:
    output: true
    permalink: /:collection/:title/
  meetings:
    output: true
    permalink: /:collection/:title/
  topics:
    output: true
    permalink: /:collection/:title/
defaults:
  -
    scope:
      path: ""
      type: "lessons"
    values:
      layout: "lesson"
  -
    scope:
      path: ""
      type: "homework"
    values:
      layout: "homework"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "meetings"
    values:
      layout: "meeting"
  -
    scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  -
    scope:
      path: "*/design-thinking"
    values:
      unit: 1
  -
    scope:
      path: "*/interaction-design"
    values:
      unit: 2
  -
    scope:
      path: "*/information-architecture"
    values:
      unit: 3
  -
    scope:
      path: "*/web-development"
    values:
      unit: 4
  -
    scope:
      path: "*/review"
    values:
      unit: 5
  -
    scope:
      path: "*/careers"
    values:
      unit: 6
relative_permalinks: false
future: false
include: ["_redirects"]
